version: '3.3'
services:
  message-broker:
    image: rabbitmq:3.8-management
    hostname: message-broker
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  service-authentication: # <--- this is the name of the service and should be unique.
    image: service-authentication:0.0.1-SNAPSHOT # <--- this is the image of which the service will be based upon.
    hostname: service-authentication # <--- this will be the hostname it will be known as.
    restart: always # <--- if it fails, always restart.
    ports:
      - 9000:9000 # <-- bind the host port 8081 to whatever is running in the container on 8080.
  service-user: # <--- this is the name of the service and should be unique.
    image: service-user:0.0.1-SNAPSHOT # <--- this is the image of which the service will be based upon.
    hostname: service-post # <--- this will be the hostname it will be known as.
    restart: always # <--- if it fails, always restart.
    ports:
      - 9001:9001 # <-- bind the host port 8081 to whatever is running in the container on 8080.
  service-post: # <--- this is the name of the service and should be unique.
    image: service-post:0.0.1-SNAPSHOT # <--- this is the image of which the service will be based upon.
    hostname: service-post # <--- this will be the hostname it will be known as.
    restart: always # <--- if it fails, always restart.
    ports:
      - 9002:9002 # <-- bind the host port 8081 to whatever is running in the container on 8080.
  service-comment: # <--- this is the name of the service and should be unique.
    image: service-comment:0.0.1-SNAPSHOT # <--- this is the image of which the service will be based upon.
    hostname: service-comment # <--- this will be the hostname it will be known as.
    restart: always # <--- if it fails, always restart.
    ports:
      - 8081:9000 # <-- bind the host port 8081 to whatever is running in the container on 8080.
  service-image: # <--- this is the name of the service and should be unique.
    image: service-image:0.0.1-SNAPSHOT # <--- this is the image of which the service will be based upon.
    hostname: service-image # <--- this will be the hostname it will be known as.
    restart: always # <--- if it fails, always restart.
    ports:
      - 8082:9000 # <-- bind the host port 8081 to whatever is running in the container on 8080.
  service-likes: # <--- this is the name of the service and should be unique.
    image: service-likes:0.0.1-SNAPSHOT # <--- this is the image of which the service will be based upon.
    hostname: service-likes # <--- this will be the hostname it will be known as.
    restart: always # <--- if it fails, always restart.
    ports:
      - 8083:9000 # <-- bind the host port 8081 to whatever is running in the container on 8080.


