apiVersion: v1
kind: Service
metadata:
  name: message-broker
  labels:
    run: message-broker
spec:
  type: NodePort
  ports:
  - port: 5672
    name: mq
    protocol: TCP
  - port: 15672
    protocol: TCP
    name: mq2
  selector:
    run: message-broker-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-broker-service
spec:
  selector:
    matchLabels:
      run: message-broker-service
  replicas: 1
  template:
    metadata:
      labels:
        run: message-broker-service
    spec:
      containers:
      - name: message-broker-service
        image: rabbitmq:3.8-management
        resources:
          requests:
            memory: "64Mi"
            cpu: "128m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 5672
          name: mq1
        - containerPort: 15672
          name: mq2
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    run: gateway
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80 
      protocol: TCP
  selector:
    run: gateway-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  selector:
    matchLabels:
      run: gateway-service
  replicas: 1
  template:
    metadata:
      labels:
        run: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: caskamp/gateway-service
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "125m"
            limits:
              memory: "1028Mi"
              cpu: "250m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: authentication
  labels:
    run: authentication
spec:
  type: NodePort
  ports:
  - port: 9000
    protocol: TCP
  selector:
    run: authentication-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
spec:
  selector:
    matchLabels:
      run: authentication-service
  replicas: 2
  template:
    metadata:
      labels:
        run: authentication-service
    spec:
      containers:
      - name: authentication-service
        image: caskamp/authentication-service
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "125m"
          limits:
            memory: "1028Mi"
            cpu: "250m"
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    run: user
spec:
  type: NodePort
  ports:
  - port: 9001
    protocol: TCP
  selector:
    run: user-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      run: user-service
  replicas: 2
  template:
    metadata:
      labels:
        run: user-service
    spec:
      containers:
      - name: user-service
        resources:
            requests:
              memory: "512Mi"
              cpu: "125m"
            limits:
              memory: "1028Mi"
              cpu: "250m"
        image: caskamp/gamehighlights-user-service
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: post
  labels:
    run: post
spec:
  type: NodePort
  ports:
  - port: 9001
    protocol: TCP
  selector:
    run: post-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
spec:
  selector:
    matchLabels:
      run: post-service
  replicas: 2
  template:
    metadata:
      labels:
        run: post-service
    spec:
      containers:
      - name: post-service
        resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "512Mi"
              cpu: "250m"
        image: caskamp/gamehighlights-post-service
        imagePullPolicy: Always
        ports:
        - containerPort: 9002
---
apiVersion: v1
kind: Service
metadata:
  name: comment
  labels:
    run: comment
spec:
  type: NodePort
  ports:
  - port: 9003
    protocol: TCP
  selector:
    run: comment-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
spec:
  selector:
    matchLabels:
      run: comment-service
  replicas: 1
  template:
    metadata:
      labels:
        run: comment-service
    spec:
      containers:
      - name: comment-service
        resources:
            requests:
              memory: "256Mi"
              cpu: "125m"
            limits:
              memory: "512Mi"
              cpu: "250m"
        image: caskamp/gamehighlights-comment-service:main
        imagePullPolicy: Always
        ports:
        - containerPort: 9003
---
apiVersion: v1
kind: Service
metadata:
  name: image
  labels:
    run: image
spec:
  type: NodePort
  ports:
  - port: 9004
    protocol: TCP
  selector:
    run: image-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
spec:
  selector:
    matchLabels:
      run: image-service
  replicas: 1
  template:
    metadata:
      labels:
        run: image-service
    spec:
      containers:
      - name: image-service
        resources:
              requests:
                memory: "128Mi"
                cpu: "125m"
              limits:
                memory: "512Mi"
                cpu: "250m"
        image: caskamp/gamehighlights-image-service
        imagePullPolicy: Always
        ports:
        - containerPort: 9004
---
apiVersion: v1
kind: Service
metadata:
  name: likes
  labels:
    run: likes
spec:
  type: NodePort
  ports:
  - port: 9005
    protocol: TCP
  selector:
    run: likes-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: likes-service
spec:
  selector:
    matchLabels:
      run: likes-service
  replicas: 1 
  template:
    metadata:
      labels:
        run: likes-service
    spec:
      containers:
      - name: likes-service
        resources:
              requests:
                memory: "128Mi"
                cpu: "125m"
              limits:
                memory: "512Mi"
                cpu: "250m"
        image: caskamp/gamehiglights-like-service
        imagePullPolicy: Always
        ports:
        - containerPort: 9005
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: vue
#   labels:
#     run: vue
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80 
#     targetPort: 80 
#     protocol: TCP
#   selector:
#     run: vue-service
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: vue-service
# spec:
#   selector:
#     matchLabels:
#       run: vue-service
#   replicas: 2
#   template:
#     metadata:
#       labels:
#         run: vue-service
#     spec:
#       containers:
#       - name: vue-service
#         resources:
#               requests:
#                 memory: "256Mi"
#                 cpu: "125m"
#               limits:
#                 memory: "512Mi"
#                 cpu: "250m"
#         image: caskamp/game-highlights-vue
#         ports:
#         - containerPort: 80
