apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
  annotations:
spec:
  rules:
  # - host: localhost
  #   http:
  #     paths:
  #     - pathType: Prefix
  #       path: /
  #       backend:
  #         service:
  #           name: vue
  #           port:
  #             number: 8080
  - host: localhost
    http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: gateway
              port:
<<<<<<< HEAD
                number: 443
=======
                number: 443
>>>>>>> 2de29d71e70a0fa0816c2772287ffe83e490b6b8
